version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: